### ISSUE TITLE
How to install/use this framework from scratch step by step with Laragon?

### ISSUE THREAD

**Issue by ProgrammingNovice** [apiato/apiato#124]
Hello,

I failed by installing/using apiato framework with laragon:
http://stackoverflow.com/questions/43002310/apiato-tutorial-example-invalid-input-the-email-field-is-required-the-passw?noredirect=1#comment73187002_43002310

Can someone explain me how to install and use this framework from scratch step by step with Laragon, please?

**Comment by Mahmoudz** [comment]
@ProgrammingNovice I do not have Windows machine, and I never used Laragon. But as far as I know it should be straightforward on any environment! anyway maybe this weekend I'll take a deeper look at your error on stackoverflow and try to figure it out, meanwhile keep trying.. Best,

**Comment by objectorientedninja** [comment]
start laragon
right click on laragon screen and choose quick create -> Laravel
name your build apiato
after everything is installed you should be able to go to apiato.dev
It also sets up a database with your build name.
so when its time to setup your .env use
db = apiato
user = root
pass = 
leave password empty since its not needed
ok now assuming you installed your project in the default location goto
C:\laragon\www\apiato
creat a folder call old
now drop and drag everything in the apiato folder into it.
now you have a empty folder (except the old folder)
while you are inside the apiato folder right click and choose Terminal
enter the following
git clone https://github.com/apiato/apiato.git
this will create a folder called apiato you need to go inside that folder and drag all contents into the C:\laragon\www\apiato
you can delete the apiato/apiato folder after you move the files. You can also delete the old folder as well at this point.
now you all all set to go with the install found at http://apiato.io/A.getting-started/installation/
while you are inside the apiato folder right click and choose Terminal
enter
composer install
then
cp .env.example .env
then 
php artisan key:generate
then
php artisan jwt:generate
now when you ran that you will see something like [jfaskdjfkdfj;kjdjf] you need to copy that - the [] and enter it in your .env
while your in the .env set up your other defaults (smtp, db etc..)
now back to the Terminal and enter
php artisan migrate
then
php artisan db:seed
then
npm install
and finaly enter 
php artisan apidoc::generate
turn restart laragon and now go to your browser and enter
apiato.dev and api.apiato.dev
Have a great time and start your journey!

**Comment by ProgrammingNovice** [comment]
@objectorientedninja , thank you very much!
