### ISSUE TITLE
How to use Events

### ISSUE THREAD

**Issue by kennethllamasares** [apiato/apiato#127]
Hi i'm just confused on how to use the events, there's a sample on the user container but i don't get it also i checked the documentation and that makes me more confuse with services (i think services has been removed), whats the rule/principle for using events, can event call action? or task? is event can only be called in action?
action->task->event?
action->event->action->task?
action->event->task?
thanks in advance.

**Comment by Mahmoudz** [comment]
@kennethllamasares some of the documentation pages are outdated, hopefully this is the last one. Anyway I just updated it now. http://apiato.io/D.components/events/

Everything should be centered around an Action. 
Actions are the use cases.
Use Case (Action) could involve firing an Event.
The Event has handler.
The Event Handler is expected to do something (Business Logic).
If we put that Business Logic inside the Event Handler itself we won't be able to use it again, unless firing that event.
So the Event Handler needs to call an Action.
Why not Task. If you are calling a single Task it's fine but still not recommended. 
Because if you decided to call another Task from that Event later, you will end up with Series of Tasks (same as in Action) inside Event, and as mentioned above the Event is not reusable outside the Event scope. So you basically end up copy pasting the same Series of Tasks. Which means duplicated code.

Example: 
In version 1 you want to send a welcome email on user registration event.
In version 2 you want to send an email and sms on user registration event.
In version 3 you want to send email and sms on user account deactivation event. 

If you have your code in Action that takes parameter the User Contact Information and the Messages Templates. You can reuse it from every Event, and also reuse it from anywhere else Like Controllers, in case you have a button (Resend).

**Comment by kennethllamasares** [comment]
thanks dude!
