### ISSUE TITLE
Production Deployment To AWS and Using AWS RDS instead of internal MYSQL docker image

### ISSUE THREAD

**Issue by Funso-Popoola** [apiato/apiato#136]
Hi,

I've so much enjoyed the blazing fast dev speed this architecture and the starter pack gives me! Thanks to y'all.

But I have an issue deploying this to AWS. I am fairly new to AWS; I've used Digital Ocean before now.
I am also new to docker but it's been fascinating since I started experimenting with it. So, I'm using Apiato and Laradock in my app.

I want to deploy my application to AWS and I want to use the standalone AWS Relational Database Service (RDS). I think that means I won't be needing the mysql image or what.

I also want to automate my deployment process using AWS CodeDeploy but I've been having trouble with specifying the buildspecs.yml .

I will so much appreciate any help I can get.

Thanks.

**Comment by Funso-Popoola** [comment]
Used the wrong account the other time, sorry. #135

**Comment by Mahmoudz** [comment]
@Funso-Popoola so you want to host your app (apiato) on Docker using Laradock on AWS.

You will have to choose between RDS and the MySQL Laradock Image. But if you're planning to use Docker, than use only Docker for everything, setting up a single EC2 instance with multiple Docker containers is very easy pretty similar to your development env. But if you plan to host docker on a cluster of instances, you will need to use some management tools to help you monitor and manage your containers. The Amazon EC2 Container Service is good place to start.

I don't think this is the right repository to ask this question, since there's nothing related to apiato in this case. I'd advise opening the issue on the Laradock repository. To get help from others who went production with Laradock..

Best,

**Comment by Funso-Popoola** [comment]
Thanks so much @Mahmoudz
