### ISSUE TITLE
API path customization

### ISSUE THREAD

**Issue by salt-lick** [apiato/apiato#154]
Instead of a subdomain (api), it would nice to be able to use the URL path instead. 

For example:

api.example.com/... => example.com/api/...

Reasoning: not everyone has easy access to update DNS records. 

[Link to RoutesLoader](https://github.com/apiato/apiato/blob/3ba97554f1cf2600cf02be429cdda70fdaa12915/app/Ship/Engine/Loaders/RoutesLoaderTrait.php#L94)

As mentioned in Slack, you could add 

`        $versionPrefix = "api/" . $this->getRouteFileVersionFromFileName($file);
`
and then change the API_URL for your .env example.com

the same goes for 

admin.example.com/... => example.com/admin/...

**Comment by akwatra** [comment]
Hi, 

I installed without docker, and modified the way as mention above about change
prefix. But http://apiato.dev:8000/api
404 error
NotFoundHttpException in RouteCollection.php line 179:

$file->getPathname(); file is there , not returning 

what is missing...?

**Comment by mlfthedifferent** [comment]
Hi,
I have modified my .env like this
![image](https://user-images.githubusercontent.com/32649152/33765779-1471283a-dc4d-11e7-91a7-49195a62168e.png)
and the apiato config file like this
![image](https://user-images.githubusercontent.com/32649152/33765831-5f2ae028-dc4d-11e7-81ec-ca39677588db.png)
that's work, the example i use artisan serve command
![image](https://user-images.githubusercontent.com/32649152/33766029-45c9936c-dc4e-11e7-9ff0-227d19830dd1.png)

But the problem when i access http://localhost:8000/api look like this
![image](https://user-images.githubusercontent.com/32649152/33766128-ac21d3e0-dc4e-11e7-8641-13770c2926b1.png)
couses i have generated apidoc to that endpoint.
After i remove /api directory at public path,  i access http://localhost:8000/api again and it work
![image](https://user-images.githubusercontent.com/32649152/33766268-5724d53a-dc4f-11e7-920c-762f8ee16aff.png)
than i can change the directory for apidoc and generate it again e.g like this 
![image](https://user-images.githubusercontent.com/32649152/33766728-61c326ac-dc51-11e7-86e9-5dc1b70f0d12.png) 
![image](https://user-images.githubusercontent.com/32649152/33766757-81c681a6-dc51-11e7-81d5-c5c0015db9f6.png)

But i still have problem with oauth endpoints 
![image](https://user-images.githubusercontent.com/32649152/33767070-c720aae6-dc52-11e7-9ab4-eeac56ebca10.png)
I have try to solve it but i can't yet.

May be others have many ideas for solving it. I'm waiting for it.
Thanks.

- Apiato version 7.2.1

**Comment by johannesschobel** [comment]
I am voting against @bingalls in this case.. I would say, it is **not** an issue to put the `version` into the URL (e.g., like this `api.com/v1/...`).  However, you need a good strategy, how to upgrade clients interacting with the API (however, this also holds true if you put the information in the headers!)

However, i do agree that putting the `version` into the header fields is more "beatiful" and more RESTful than other approaches.. With this information in mind, however, you should think about, **who** (target group) will use your API..
- If it is used by developers who are familiar with REST calls and http headers and so on, you may easily put respective information into headers, because they most likely know how to properly use this
- If it is used by developers who rarely got into contact with REST and headers, but know how to call a certain URL, you may want to put it into the URL, because they "already know how to deal with it"..

Just my two cents on this.. 

In general, `Versioning` with respect to APIs is also cumbersome and nerv-wrecking :laughing:
