### ISSUE TITLE
Social login 

### ISSUE THREAD

**Issue by R00118189** [apiato/apiato#160]
Hey @Mahmoudz ,

I would like to suggest enhancement social logins to be decoupled from user model and have its own to allow for multiple social network login for the same user. 

Cheers
Bart

**Comment by Mahmoudz** [comment]
@R00118189 that sounds great, that container needs some refactoring anyway. If you have some time to submit a PR would be awesome. It's been a long time since I used that container.

**Comment by anthonymartin** [comment]
This feature is completely broken. No part of it is working on my installation. After resolving many errors, I think I'm closer to making it work. Am I missing something - is social login really supported on this package because it seems like I've had to do a lot of work to get to where I am, yet the Socialauth container is still unable to create or update the user. 

I'm curious if any work has been done to decouple the user model to allow for multiple social network login for the same user. Perhaps I can contribute.

What's the best practice if an email associated with a 3rd party OAuth is found, but that social auth provider has not been used for login before? For instance, if a record in the users table is found with the same email that an OAuth provider returns, but that OAuth provider hasn't been used for authentication before - should the container return an error asking the user to login with their usual authentication method?

**Comment by Mahmoudz** [comment]
@anthonymartin I've implemented this feature and used a long time ago. I haven't tested it since then. So it might be broken. It will need some updates as the Socialite package has been updated.. I'd appreciate your contribution on this. 

Regarding your last question. I'm not sure what's the best practice for this case, however I remember facing similar situations. I would go with whatever works best for you.

**Comment by ralphstodomingo** [comment]
I've been trying to get my hands wrapped around Apiato, and yep the socialauth container needs work. It doesn't work out of the box, and Google isn't really supported like the docs say. I wish I had more understanding of how this is supposed to work and I might be able to contribute. Anyone else doing work on this already?

@anthonymartin In my experience: you sign-up with Facebook, login with Google and it leads to the same account.

**Comment by johannesschobel** [comment]
@Mahmoudz i am not sure, if this can be closed since you refactored the `SocialAuth` container?!
