### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by Mohamed-Zedan** [apiato/apiato#169]
Hello Mahmoud, 
Ramadan Kareem :)

I am trying to install your project on homestead, but when I open apiato.dev or admin.apiato.dev I got this message No input file specified.

According to documentation, running this command " vagrant halt && vagrant up --provision "
but still showing this message.

*note: api.apiato.dev in working.

**Comment by Mahmoudz** [comment]
@Mohamed-Zedan Hi and Ramadan Karim :) 

Well that's usually caused by some missed configuration either from Homestead or NGINX.

I would say re-check the Homestead config file and re-run `homestead halt && homestead up --provision`. If that didn't help try to edit the NGINX config file. 

There are many possibilities for such error, I advise seeking google's help :P 

If there is any problem with the installation steps in apiato's docs please inform me to update it.

Best,

**Comment by Mahmoudz** [comment]
@Mohamed-Zedan after checking the docs now, I think you're possibly doing something wrong by pointing to non existing directories so try the following instead:

```
    - map: api.apiato.dev
      to: /{full-path-to}/apiato/public
    - map: apiato.dev
      to: /{full-path-to}/apiato/public
    - map: admin.apiato.dev
      to: /{full-path-to}/apiato/public
```

**Comment by Mohamed-Zedan** [comment]
@Mahmoudz 
 Thanks a lot my friend, now it's working <3 .

**Comment by Sanchita-12345** [comment]
@Mahmoudz can you please inform where in the homestead config file?
