### ISSUE TITLE
Tests failing for a fresh install

### ISSUE THREAD

**Issue by envision** [apiato/apiato#179]
Am getting 10 errors when testing a fresh install. Double checked by making a new project and configured database config only, then got also 10 errors + 1 failure. That one failure was probably for not configuring urls.

    ERRORS!
    Tests: 45, Assertions: 108, Errors: 10.

	10) App\Containers\User\UI\API\Tests\Functional\UpdateUserTest::testUpdateExistingUser_
	TypeError: Argument 2 passed to PHPUnit\Framework\Assert::assertThat() must be an instance
	of PHPUnit\Framework\Constraint\Constraint, instance of 		
	Illuminate\Foundation\Testing\Constraints\HasInDatabase given, called in 
	/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithDatabase.php on line 22

**Comment by Mahmoudz** [comment]
@envision I just tested a fresh installed copy and couldn't reproduce your error. However it seems that your problem is coming from the database settings on your machine. We're supposed to be using SQLite for the tests and seems that have a problem somewhere with that!!

That line is the source of your error, try to debug it to find out the reason or check if there's anything in the log files:

```php
        $this->assertThat(
            $table, new HasInDatabase($this->getConnection($connection), $data)
        );
```

**Comment by envision** [comment]
Thank you @Mahmoudz, got it solved with your tip. Error was misleading so didn't notice to suspect the setup.
