### ISSUE TITLE
Testable without tests

### ISSUE THREAD

**Issue by Dylan-DPC** [apiato/apiato#208]
## Expected Behavior
my app will be testable

## Actual Behavior
My app won't be testable cause the framework itself doesn't have any tests

## Steps to Reproduce the Problem

  1. Do whatever you want
  2.
  3.

## Specifications
 

  - Apiato Version: *.*

## Additional Details

How will i know my apps will be scalable and testable? considering for the fact that "framework" isn't tested.

**Comment by Mahmoudz** [comment]
In case you haven't found the tests, they live in each container at `app/Containers/{container-name}/UI/API/Tests/Functional/` and `/app/Containers/{container-name}/Tests/Unit/`.

So all the endpoints provided by the framework are functionally tested. And if you are referring to Unit testing the Core Package, this was extracted from the framework today, and unit tests are on the way.

In addition, the framework provide it's users with [helper functions and features](https://github.com/apiato/core/tree/master/Traits/TestsTraits/PhpUnit) to facilitate writing their functional and unit tests. 

Scalability comes from the architecture itself. And testability comes from the easy way of writing tests within the framework.

If you are a lazy developer (and apparently you are, since you haven't removed the empty 2 and 3  points under "Steps to Reproduce the Problem"), then this framework might not be the best tool for you.

**Comment by Dylan-DPC** [comment]
> If you are a lazy developer (and apparently you are, since you haven't removed the empty 2 and 3 points under "Steps to Reproduce the Problem"), then this framework might not be the best tool for you.

You missed the point didn't ya? Isn't that the whole point of the framework is to make it easier for people to develop apps? if developers weren't lazy they would sit and build their own instead of relying on something with claims on the moon.

**Comment by ConnorVG** [comment]
@Mahmoudz 

>If you are a lazy developer (and apparently you are

That is a very cunty thing to say, mate.

The entire layout and naming of this app is very bizarre... What was the driving point behind hiding your tests?
