### ISSUE TITLE
RFC - Socialauth, REST Generator, Apiato Private API Client

### ISSUE THREAD

**Issue by anthonymartin** [apiato/apiato#222]
Seeing as the Socialauth container here is broken I'm thinking about contributing to the Apiato project to help fill in some gaps.

These are my thoughts and your comments are appreciated.

1. Create `social_profiles` table that will have a foreign key to `users.id` - a user can have multiple social logins per account.
2. Create REST code generator for Apiato. I think I've identified the following endpoints and files which would need to be created when a user wants to create REST endpoints for a given model. This would boost the speed of development. To do this, I'm looking to fork [InfyOmLabs/laravel-generator](https://github.com/InfyOmLabs/laravel-generator) - any help or ideas to move this faster along would be appreciated. Can someone like @Mahmoudz tell me if these are all the files I need to generate a REST endpoint in apiato?
```
	Routes:
		GET /$ModelName              | app/Containers/$Container/UI/API/Routes/$ModelName.Index.$EnpointVersion.$TypePubOrPriv.php
		GET /$ModelName/{id}		 | app/Containers/$Container/UI/API/Routes/$ModelName.Show.$EnpointVersion.$TypePubOrPriv.php
		POST /$ModelName 			 | app/Containers/$Container/UI/API/Routes/$ModelName.Create.$EnpointVersion.$TypePubOrPriv.php
		PUT /$ModelName/{id}		 | app/Containers/$Container/UI/API/Routes/$ModelName.Update.$EnpointVersion.$TypePubOrPriv.php
		DELETE /$ModelName 			 | app/Containers/$Container/UI/API/Routes/$ModelName.Delete.$EnpointVersion.$TypePubOrPriv.php

	Request:
		$ModelName.IndexRequest  	 | app/Containers/$Container/UI/API/Requests/$ModelName.IndexRequest.php
		$ModelName.ShowRequest		 | app/Containers/$Container/UI/API/Requests/$ModelName.ShowRequest.php
		$ModelName.UpdateRequest	 | app/Containers/$Container/UI/API/Requests/$ModelName.UpdateRequest.php
		$ModelName.DeleteRequest	 | app/Containers/$Container/UI/API/Requests/$ModelName.DeleteRequest.php

	Controller:
		$ModelNameController@index   | app/Containers/$Container/UI/API/Controllers/$ModelName.Controller.php
		$ModelNameController@create
		$ModelNameController@update
		$ModelNameController@show
		$ModelNameController@destroy

	Actions:

		Index.$ModelName.Action 		| app/Containers/$Container/Actions/$ModelName.IndexAction.php
		Create.$ModelName.Action 		| app/Containers/$Container/Actions/$ModelName.CreateAction.php
		Update.$ModelName.Action 		| app/Containers/$Container/Actions/$ModelName.UpdateAction.php
		Destroy.$ModelName.Action 	 	| app/Containers/$Container/Actions/$ModelName.DestroyAction.php

	Model:

		$ModelName.Model				| app/Containers/$Container/Models/$ModelNameModel.php

	Repository:
		$ModelName.Repository			| app/Containers/$Container/Repositories/$ModelNameRepository.php

	Tasks:
		
		Update.$ModelName.Task 		| app/Containers/$Container/Tasks/$ModelName.UpdateTask.php
		GetAll.$ModelName.Task 		| app/Containers/$Container/Tasks/$ModelName.IndexTask.php
		Create.$ModelName.Task 		| app/Containers/$Container/Tasks/$ModelName.CreateTask.php
		Destroy.$ModelName.Task 	| app/Containers/$Container/Tasks/$ModelName.DestroyTask.php

	Transformers:
		$ModelName.Transformer      | app/Containers/$Container/UI/API/Transformers/$ModelName.Transformer.php
```
3. Write guzzle-based API client which would interact with the endpoints in point 2 above. As endpoints are written in Apiato, it makes sense to utilize those endpoints as much as possible instead of creating more actions and tasks. For instance, it makes sense to create REST endpoints for `social_profiles` CRUD functionality and to consume that endpoint for the new Socialauth container.
The Apiato Private REST API Client I'm proposing would be configurable within the app configuration and would essentially act as a OAuth 2.0 REST client that will handle internal apiato requests to apiato endpoints. For instance, to generate a new `social_profile` table record in the Socialauth container, I would call `$ApiatoPrivateRestAPI->post('/v1/social_profiles', $data);` - If future development is done in this manner, I believe upgrades could be easy and powerful in the future.

**Comment by Mahmoudz** [comment]
@anthonymartin nice proposal.

1) The `social_profiles` is good.

2) We do have a Components generator in Apiato, what are the advantages of using that package instead? or how are you planning to use them both together? I would suggest here to add more features to our generator to be able to generate a full container as this is not yet implemented and it would be a very nice feature.

3) Interacting with endpoints instead of classes to communicate between Containers like in micro-services architectures seems a good idea but I don't recommend it as it will slow the Application and makes it hard to debug things. Whenever you'll change the signature of an endpoint you'll have to update everyone using it anyway. In addition, depending on Interfaces is better than depending on endpoints in this case as Interfaces allows detecting the dependencies problems by interpreter.

let me know what you think and if I missed anything.

**Comment by johannesschobel** [comment]
Hey @anthonymartin and @Mahmoudz .. Just wanted to drop my thoughts as well..

1) i think that would be a good idea. I wanted to re-structure / refactor the `SocialAuth` container as well, but I do not know enough about the general `Auth Flow` with 3rd party services like Google, Facebook and so on..

2) APIATO already offers a lot of generators that allow you to auto-generate code. I use them all the time - they allow you to blazingly fast bootstrap your API. See [this link here](http://apiato.io/features/code-generator/) for more infos in the docs.
You can basically call the following comands:
```bash
php artisan apiato:<ENTITY>
```
with `<ENTITY>` be one of the following ones:

- model
- controller
- transformer
- action
- subaction
- task
- repository
- ...

Just call `php artisan` to show you all available commands. 
If you need a dedicated command that bootstraps / generates a whole container, just create your own `Command` and put it in `App\Ship\Commands` where it gets auto-loaded and auto-registered. Then combine the already existing artisan commands to your need..

3) I think, the `MicroService` idea is quite sexy, however, I don't think that it is possible "out of the box". What i think, you need to do is the following think:

- Create multiple APIATO instances that contain only the specific containers you want to offer in those "applications" and correctly "name" them. E.g., you then would have a 
```bash
core.apiato.dev -> contains an "empty" apiato installation with the predefined containers, like auth, user, roles, ...
shop.apiato.dev -> contains a "shop" container with all its routes, ...
products.apiato.dev -> contains the "products", ...
x.apiato.dev -> contains whatever
```

All these applications must contain the `App\Ship` as well as the core and so on.. And can be installed on separate machines (as they are exposed through different subdomains). Furthermore, a client that wants to login requests `core.apiato.dev/auth/login` and gets a response from this dedicated server. However, a User browsing the Shop requests the `shop.apiato.dev`, while this endpoint then calls the `products.apiato.dev`.. And there you have it - your `MicroService` architecture.

However, this would require significant modifications of an already existing application, as you need to "wire it all together".. Basically, when calling something from another container (that does not belong to the current "application" (e.g., the shop that requests product information from the example above)) your `$this->call(...)` must be changed to an `Guzzle HTTP Call`.. But that should be manageable ;)

Just my 2 cents..
Cheers

**Comment by anthonymartin** [comment]
Thanks for the feedback everyone. 

Ideally I'd like for there to exist a CRUD generator. For example, when I add a new model to the project, generating all CRUD operations will be as simple as calling one crud generator command that makes RESTful endpoints automatically with `role=admin` permission by default. This would mean that this API generator would work "out of the box" so long as the user is utilizing the built-in user model and authentication. The generated endpoint would still be secured against unauthorized use. 

The added benefit that I see is the ability to utilize those generated endpoints immediately which all have documentation with known responses. When a task or action returns a response (not in the `class Response` sense of the word), I don't always know if it's a boolean, an array, or an object, and the data structure is usually unknown. That means if I only consume the generated endpoint using an HTTP request, I will always know the type of response to expect. Therefore the responses provided within the entire application will be standardized. This does come at the expense of speed, because of additional HTTP requests that are taxed with bootstrapping the application again. I feel this application performance tradeoff serves to enhance rapid application development, extensible interoperability and general adoption of Apiato.

My desire for the CRUD generator really stems from this frustration that although the following items and more are supported:
```
Query Parameters support (orderBy, sortedBy, filter, include) with full-text search (search, searchFields).
Auto encoding/decoding of real ID's, to prevent exposing real ID's to the outer world.
API Throttling (Rate Limiting).
Exception handleing with custom JSON errors responses.
```
None of those items are actually enabled by default - I need to "wire it all together" as @johannesschobel mentions. The CRUD generator would take care of all of that wiring.

**Comment by johannesschobel** [comment]
Hey @anthonymartin ..

The QueryParameters and so are enabled by default by the `l5-repository` package that is included in apiato. `HashID`s work "out of the box" - you just need to set them in your `Request` class to be decoded (just one line in a respective array). `APIThrottling` is enabled by default for all api routes (not 100% sure but i think so) and `Error Responses` can by tackled by `Exceptions`...

As I would highly appreciate a "_generate everything out the box_" generator, I do believe, that a such a generator is not "generic" enough to suit a the vast majority of application scenarios and must be tailored to your specific needs.

As i am the one, that has re-written most of the `Generator` package in the core, I will put some more light on this topic. At the time, I was refactoring the existing Generators (I think, at this time, only 2-3 existed), and adding the others, I thought about adding such a `CRUDGenerator` as well. However, when I thought about it, I realized that it may not be feasible, because of the following aspects:

- First, there is so much business logic involved that determines what entities are shown (e.g., based on the current user, permission, ...). When using the `Repository` pattern from APIATO, this requires to create (and append) the correct `Criteria` to the repository that does this for you.
- Second, the `Validation` of the `Request` class to be auto-generated based on the model is a mess! Just adding `=> 'required'` to each field with is not enough. You need to determine the datatype (e.g., `string|boolean|integer|array`) and add additional restrictions (e.g., `min:5|max:100`). Furthermore, specific fields must only be present, if others are set, ...
- Third, depending on your `Request Format` and "Style" (e.g., raw application/json or x-form-www-encoded, ...) the structure of the request to be parsed is different. I, for example, use JsonAPI Style everywhere - so the data that is sent to the webservice looks like this:
```json
{
   "data" : {
      "type" : "User",
      "attributes" : {
         "name" : "John Doe",
         "email" : "john.doe@example.com",
         "admin" : true
      }
   }
}
``` 

Therefore, my validation rules look like this:
```php
$rules => [
   'data.attributes.email' => 'required|email',
   // ... 
]
```
I need to add `data.attributes.` to all keys in order to match the JSON API Schema. However, if you rely on `x-www-form-encoded` data your validation rules might look different.

- Fourth, same for the output (You use `DataArraySerializer, I use `JsonApiSerializer`, ... ).
- Fifth, ...

----------------------

Please note that most of the existing generators do provide flags to generate "more than the usual" code. - E.g., the `apiato:transformer` is capable of creating a transformer that contains all fields of the model (based on the database structure). However, it is not possible to generate the "relationships" as well (e.g., User has Roles, User has Permissions) - if you like these information, you must add it themselves.
- The `apiato:controller` generator may generate the CRUD stubs for the methods, however, you need to "add life" to these.
- The `apiato:model` generator may creates the corresponding `Repository`...
- The `apiato:event` generator creates the corresponding `Listener`...

In my opinion, a `apiato:crud` generator would be nice to have, but way to specifically tailored for your application in order to allow for a generic use in other applications. This starts by your specific naming conventions, continues with the way how you validate / sanitze data in requests, how you structure the code internally, and so on.. Finally, your mentioned approach would rely on the fact, that you know your entire `Model` right from the start - what if i need to change my model during development time (e.g., rename `name` to `title` to better describe its nature, add a field `description` or change the type from `int` to `boolean`). 

----------------

I think, we need to distinguish 2 different types of "create everything" `CRUDGenerator`s:

1) A `CRUDGenerator` that mainly calls the already existing Generators in order to create empty stubs that has to be implemented by the developer.
2) A `CRUDGenerator` that does all the work for you, applies correct `Validation`, creates `Criteria` and so on..

Regarding 1) I think, this is possible and feasible.

----------------

You can try to implement a `CRUDGenerator` and add it to `App\Ship\Commands`. Commands in this folder are autoloaded and you can test it immediately :)

You can easily combine the already existing generators to a new one to create everything out of the box. Your new command must `extend GeneratorCommand` in order to use its "wizard-based style". Furthermore, you can call other commands from your generator like this:
```php
Artisan::call('apiato:repository', [
                                    '--container' => $this->containerName,
                                    '--file' => $this->fileName . 'Repository'
```

This calls the `apiato:repository` command and adds the params for `container` and `file`.. So basically these steps are ommited from the wizard from the `repository` generator.

-------------------

Just a final remark:
REST, by default, has the "problem", that you do not know the structure of the `Request` and / or `Response` messages, because there is no `Contract` like in SOAP (for example, by using `WSDL` files). There are approaches (`WADL`) that try to fix this issue, but it is no established standard and not vendor-neutral. Furthermore, REST Web Services tend to be more "dynamic" (i.e., they evolve more quickly) than SOAP services. If you would like to auto-generate a doc for your webservice, this means that you need to _read_  the information of your `Validator` class in the `Request` to automatically determine which fields are required and so on. This, obviously, catches only the fields that are defined in the `Validator`. Same for the `Response` of an endpoint (think about the different Serializers!)

**Comment by johannesschobel** [comment]
Oh.. and another comment..
I am aware of the `laravel-generator` package. However, i do not know, if adding all inforation (e.g., the name of all model attributes, validation rules, ...) via console input is so nice to handle..

Doing it on a code-basis allows you to undo / redo things, fix typos and so on..

**Comment by johannesschobel** [comment]
take a look at [this here](https://github.com/apiato/core/pull/13)

**Comment by anthonymartin** [comment]
@johannesschobel - amazing!!!!! thank you :)

**Comment by johannesschobel** [comment]
You are welcome.. I've added another PR that lets you "override" the stubs with your own in order to customize them to your needs.. at least a little bit ;)

**Comment by johannesschobel** [comment]
i think this one can be closed?!
