### ISSUE TITLE
generate task command getone stub missing

### ISSUE THREAD

**Issue by yalsicor** [apiato/apiato#280]
Hi,

I am not sure wether to post this here or in apiato core, since the code for this lives in apiato core?

When I try to generate a Task with GetOne stub I get:
 [Illuminate\Contracts\Filesystem\FileNotFoundException]                                                                              
 File does not exist at path [...]/vendor/apiato/core/Generator/Stubs/tasks/getone.stub

This is fixed in line 81 in apiato/core/Generator/Commands/TaskGenerator.php:
`['Generic', 'GetAll', 'GetOne', 'Create', 'Update', 'Delete'],`
to:
`['Generic', 'GetAll', 'Find', 'Create', 'Update', 'Delete'],`
since getone.stub seems to be renamed to find.stub.

I am not sure, how to contribute such bugfixes, I am somewhat new to the game.

Thanks, Yal

**Comment by johannesschobel** [comment]
hey there.. that is a good catch.. i can fix it tomorrow - no problem! if this is merged you just need to `composer update` to get the latest version..

**Comment by yalsicor** [comment]
How can I create that PR myself?

**Comment by johannesschobel** [comment]
Hey there.. I just made the PR as i was already developing something else.. 

Ok, to answer your question:
1) you need to fork the `apiato/core` to your github user (this repo will then be called `yalsicor/core`)
2) clone your `yalsicor/core` to your local computer
3) make a new branch that describes your changes (e.g., `fix stubs`)
4) start making the changes and create meaningful commits
5) push the commits back to `yalsicor/core`
6) go to `apiato/core` and then you get the possibility to create a PR for `yalsicor/core:fix_stubs` to `apiato/core:dev-master`
7) explain what you have done

However, the problem here is, that you also need to clone `apiato/apiato` to your user. This `apiato/apiato` also needs to be cloned to your computer and so on. Furthermore, you must use "your" `yalsicor/core` in your `yalsicor/apiato` in order to test the changes accordingly.

At least, thats what i do, when I contribute to apiato..

**Comment by yalsicor** [comment]
Thanks a lot, I will do so.

**Comment by Mahmoudz** [comment]
@yalsicor just run composer update, should be fixed, thanks to @johannesschobel https://github.com/apiato/core/pull/30
