### ISSUE TITLE
[Question] Separation of Frontend and Backend

### ISSUE THREAD

**Issue by arosenhagen** [apiato/apiato#302]
wrapping my head about the concepts, I found this comment quite misleading:

> Apiato does not recommend serving HTML pages. Instead you should build your own Frontend App completely isolated from the Backend code.`
> http://docs.apiato.io/features/admin-dashboard/

Does that mean, that Apiato differs from [Porto](https://github.com/Mahmoudz/Porto#Views) in this regard - or more precise: what's the Views/UI then?!

Is your advise here to only build "the Backend" say Database/Business Logic/API with Apiato and separating any "Frontend" be it an (Web)Admin-Area or a public Frontend or an App etc. in a complete isolated project (which may be in a totally different language as it has no knowledge about how "the Backend" is build)?
Also when providing a Web-UI for the configuration of the backend itself (starting with admin dashboard and further user management, API-Access/Authorization) this should live outside of Apiato?

**Comment by justdayan** [comment]
Just chiming in here on a general note. I'm seeing that using a rest api is more and more the way we should go, and the backend should be completely headless. It gives you 1000x amount of freedom. It also means more custom front end code. I THINK that's good. Since the recession, employers have shown that they want us to be Full Stack, so that they can save costs on overlapping developers by employer single stacks. That rationality has proved a failure. It only means they're offloading their technical debt onto us. However.... if you're full stack, you're 10x. You have the means to achieve a more solid solution. It may not be SOLID. It may just be more affective.

My advise is, build your backend as an API so it can be consumed by anything.

**Comment by Mahmoudz** [comment]
arosenhagen Hi, The Porto architecture does support any kind of UI (Web is fine if you wanna structure your web profile it will be fine). However, in the Apiato project it's not recommended to have the Web as part of the API, as @justdayan mentioned. But we do support it, for those who needs it. Probably for few simple pages or even full front end implementation. Hope this makes it clear.
