### ISSUE TITLE
inconsistent behavior with transformers

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#309]
This got me confused today:
In the controller the transforming goes like this:

> $this->transform($user, UserTransformer::class);

while in the transformer class itself you transform like this:

> $this->collection($user->roles, new RoleTransformer());

(note that the collection/item method does almost exactly the same as the transform method)
Is there a reason why the type for the second argument is different?

**Comment by johannesschobel** [comment]
Hey there.. This is mainly, because "embedding" resources within a transformer (i.e, use the magic `includeX` methods) is a feature that is provided by `Fractal` (a 3rd party package) and not Apiato itself..

I think, the main reason is, because Apiato used to call everything using the `::class` style.. So there is the difference ;)

**Comment by Kyslik** [comment]
I was meaning to ask, are any known issues with n+1 problem while using includes? https://www.google.com/search?q=n+1%20problem%20laravel&cad=h

**Comment by johannesschobel** [comment]
Of course including additional information may be resource-heavy. However, usually the client can decide on its own, if he would like to request more data in his request.. Finally, using `include` would be faster / better than making additional requests..
