### ISSUE TITLE
How to use Transformer with stored procedure

### ISSUE THREAD

**Issue by overbid** [apiato/apiato#310]
My project execute via stored procedure without model. How to work with Transformer?

**Comment by johannesschobel** [comment]
Hey @overbid .. I had this issue in another project as well. This was, however, not in the context of an Apiato project, but with Laravel 5.x (5.1, i think).

Thereby, i solved this as follows:
I created a common class (`stdClass`) or make a custom class (`MyCustomClass extends stdClass`) and add data to an object of respective class.

Then, I passed this object to the Transformer - and voila - you're ready.. Should work..

You may try to use `ValueObjects` from apiato for this as well (`php artisan apiato:generate:valueobject`) in order to generate a class that does not a (Eloquent) `Model`.

Cheers,

**Comment by johannesschobel** [comment]
hey @overbid .. can you give feedback about this issue? has the provided idea solved this issue for you?

**Comment by overbid** [comment]
No. It's show didn't know getResourceKey().

**Comment by johannesschobel** [comment]
@overbid you can manually set the `resourceKey` in the `->transform()` call in the Transformer.. i don't know which parameter it is (4th i think...)

**Comment by johannesschobel** [comment]
@overbid however, thanks for the info regarding the `ResourceKey`.. I will add this to the core in order to automatically provide the same functionality like in the `Model` classes..

**Comment by johannesschobel** [comment]
Ok, short update on this @overbid : 

I just installed the latest Apiato application and created a new `ValueObject` called `Foo` in the `User` container with `apiato:generate:valueobject`. This `ValueObject`, in turn, already has the `protected $resourceKey` correctly set. Then i added a random field to this `ValueObject` and assigned a value hard-coded.

Next, i created a `FooTransformer` in the same container and manually passed the `Foo ValueObject` to this transformer..

Note that i had to remove `$entity->getHashedKey()`, as the `ValueObject` does *not* have the respective Trait.

When i called the route, everything was fine for me!

Please note that the `ValueObjects` already have the correct `HasResourceKeyTrait` trait assigned - so you should be able to set it accordingly!

Hope this helps - can you give feedback!?

**Comment by johannesschobel** [comment]
Please note that valueobjects got renamed to values in the latest version..

**Comment by johannesschobel** [comment]
@overbid any news on this one?

**Comment by overbid** [comment]
Sorry for no response. I haven't test it. I'm looking for another project. sorry.

**Comment by johannesschobel** [comment]
No Problem, good luck!

**Comment by overbid** [comment]
I try it now and found example code in https://github.com/apiato/apiato/tree/master/app/Containers/Localization. It's work.
