### ISSUE TITLE
[Question] Dropping repository pattern

### ISSUE THREAD

**Issue by Kyslik** [apiato/apiato#320]
Repository pattern feels so wrong - useless, rewriting Eloquent functionality all over again. No one does mocking anymore (have you seen https://adamwathan.me/test-driven-laravel/), switching implementation is not real since, repositories return Eloquent models instead of `stdClass` or `array` or whatever "repository" pattern recommends. 

I really like criteria - scopes (BTW: it should be "criterion" singular, and "criteria" plural) and caching but thats easily done using specific package for that.

---

The question: Is [l5-repository](https://github.com/andersao/l5-repository) hard-coded in "core" of this framework or it can be cut out easily. I know I can search https://github.com/apiato/core/search?p=1&q=repository&type=&utf8=%E2%9C%93 but I am asking whoever knows all internals of the Apiato framework if its recommended to cut it out on Ship/Container level.

**Comment by johannesschobel** [comment]
Hey there.. Actually, I don't think, that it "re-implements the whole Eloquent functionality".. Actually, it adds an additional layer over Eloquent.. Besides this - `Criteria`, `Scopes` and so on are really, really helpful!

We are aware of the fact, that it should be called `Criterion` - however, renaming all existing `Criteria` will result in a breaking change ;) That will be something for Apiato 8.0, I would guess..

As far as i know, the repository pattern is quite hard-woven into the core - but i am not entirely sure about this..

**However**, and here is my point... You are absolutely free to **not** use `Repositories` at all.. For example, in a `FindUserByIdTask` simply do a `User::where('id', '=', $id);` instead of calling the `UserRepository->find($id)`.

If you use the `Generators` in apiato quite often, you might want to override the predefined Stubs (there should be a `CustomStubs` folder in `App/Ship` somewhere, where you can override them). There you can add your own code - if you then run `php artisan apiato:generate:task` the custom stubs are used instead of the default ones.. Makes it easy for you to customize..

Hope this helps!?

**Comment by Kyslik** [comment]
Yea this helps a ton! :)

Oh yea, I love criteria feature of the l5-repository package, its really nice. I know that it also provides some neat features like search, filtering etc.. but I have my own [code](https://github.com/Kyslik/laravel-filterable) for that already (not peer tested yet).

**Comment by johannesschobel** [comment]
oh well.. then just "skip" the `Repository` by simply using `Eloquent` and adapt your stubs to your custom needs. Might be the easist / fastest solution,..

Can this issue be closed? ;)
