### ISSUE TITLE
Where are the broadcasting routes?

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#327]
I looked over the documentation & in the whole project but i couldn't find the right place to put my broadcast routes. Where are they :) ?

**Comment by johannesschobel** [comment]
hey, yesterday someone asked the same thing on slack.. i don't think, there are any broadcast routes available for now..

**Comment by deviouspk** [comment]
Oh. Hmm how do we implement broadcasting authentication then :p

**Comment by Mahmoudz** [comment]
@deviouspk I just added that, go to this file https://github.com/apiato/apiato/blob/master/app/Ship/Boardcasts/Routes.php and start adding your routes. I also documented it here http://docs.apiato.io/components/events/#Broadcasting. Best,

**Comment by mertyildiran** [comment]
@Mahmoudz hi, I would like to resurrect this issue because; as of https://github.com/apiato/apiato/commit/368daffb7f7a8118c58bf25bb3031930b533c046 `Broadcast::routes()` in [here](https://github.com/apiato/apiato/blob/368daffb7f7a8118c58bf25bb3031930b533c046/app/Ship/Parents/Providers/BroadcastsProvider.php) does not really register the `/broadcasting/auth` route as it's described in [Laravel's documentation](https://laravel.com/docs/7.x/broadcasting).

Probably the modified route loading mechanism of Apiato is conflicting with `Broadcast::routes()` but I couldn't figure out the root cause yet.
