### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by Toosure** [apiato/apiato#353]
## Actual Behavior

http://admin.apiato.dev returns the same page as apiato.dev
After configuring my apache2 server 
Host conf file to

127.0.0.1	api.apiato.dev
127.0.0.1	apiato.dev
127.0.0.1	admin.apiato.dev

And setting up my virtual host

<VirtualHost *:80>
	DocumentRoot "PATH/TO/YOUR/PROJECT/public"
	ServerName apiato.dev
	ServerAlias apiato.dev
	
	<Directory "PATH/TO/YOUR/PROJECT/public">
		Options Indexes FollowSymLinks Includes ExecCGI
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>
<VirtualHost *:80>
	DocumentRoot "PATH/TO/YOUR/PROJECT/apiato/public"
	ServerName api.apiato.dev
	ServerAlias api.apiato.dev
	
	<Directory "PATH/TO/YOUR/PROJECT/apiato/public">
		Options Indexes FollowSymLinks Includes ExecCGI
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>
<VirtualHost *:80>
	DocumentRoot "PATH/TO/PROJECT/apiato/public"
	ServerName admin.apiato.dev
	ServerAlias admin.apiato.dev
	
	<Directory "PATH/TO//PROJECT/apiato/public">
		Options Indexes FollowSymLinks Includes ExecCGI
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Apiato Version:

**Comment by johannesschobel** [comment]
I think, you need to specify the `www` subdomain instead of the `` (empty) one.
Further, what route are you calling? There is only one basic "login" form for the admin.. Please type
`php artisan route:list`
in order to see all available routes. Then look out for the "admin" prefix (don't know the column name) and call such a route in your webbrowser. Those routes, however, should start with `admin.` in the URL.. 

Hope this helps?!
