### ISSUE TITLE
Folder Structure -  Eloquent Events Model file inside apiato.

### ISSUE THREAD

**Issue by RaphaelAugustos** [apiato/apiato#355]
Hi!

Where I'can put the eloquent model observer files inside apito? Look this example from [gitscrum-community-edition](https://github.com/gitscrum-community-edition/laravel-gitscrum/tree/master/app/Observers) and the oficial [Eloquent Events documentation ](https://laravel.com/docs/5.5/eloquent#events).

I'm try to convert [gitscrum-community-edition](https://github.com/gitscrum-community-edition/laravel-gitscrum/tree/master/app/Observers) project to apiato framework.

Thanks in advanced.

**Comment by johannesschobel** [comment]
Hey there..

Porto (Apiato is an implementation of this architecture) suggests to store `Events` in `App\Containers\XXX\Events`. There is a also a generator to create such basic events: `php artisan apiato:generate:event`. You can execute this command in order to get more details on how they work.

Hope this helps?!
Cheers

**Comment by rAugustos** [comment]
Thanks in advanced!

**Comment by johannesschobel** [comment]
Glad it helped you!
Can you close this issue, if it solved your problem :) thank you very much!

**Comment by rAugustos** [comment]
The option 'close' doesn't appear x(. Can you close to me?

**Comment by johannesschobel** [comment]
Sure ;)

**Comment by Kyslik** [comment]
Its because you have multiple accounts @rAugustos  is different than @RaphaelAugustos
