### ISSUE TITLE
Introduce Sections to allow grouping of containers ?

### ISSUE THREAD

**Issue by GERJohnson** [apiato/apiato#382]
Currently in Apiato there a two payment providers at top note: Stripe and WePay. in a large app there might be even more payment providers like: Braintree, In-App, Crypto, etc. This will lead into a lot of folders.

I feel it would be more organised if we could group containers in "Sections". So the Payment Container could look like this.

What do you think ?

App
......Containers 
...........Authentication
...........Payment
................Actions
................**Section** 
....................Stripe
.........................Actions
....................WePay
.........................Actions

**Comment by strainovic** [comment]
I agree with you. It could be really messy once you have dozen containers of the same type. By nature, they should be grouped together.

+1 for sections

**Comment by johannesschobel** [comment]
Hey there,

funny thing is - i thought about this 2-3 months ago.. However, i wanted to add it on the "top" level (e.g., add another `Admin` folder beside `Containers` and `Ship`). So my structure would have been:
```
app
   Admin
      // your container related to the admin subdomain here
   Containers
      // the normal apiato containers
   Ship
      // the normal ship
```

However, i quickly ran into huge problems.. Mainly, because you this involves "duplicating" nearly all of `apiato/core` because of the `Loaders`. Apiato uses custom `Loaders` (not the default ones from `Laravel`), because it has a more advanced structure than normal `Laravel` applications have..

I think, this would be a "nice to have" feature, but it is not "crucial". Nothing, you would not be able to achieve with a good documentation of your application structure.

If i find time, i can look into the `SubContainers` idea you described above. However, this will - most likely - also result in rewriting significant parts of the core.. However, i'll give it a try..

**Comment by GERJohnson** [comment]
awesome... Another idea could be to just introduce sub-Containers. 

So the structure would be:


App
......Containers
...........Authentication
...........Payment
................Actions
................**Containers**
....................Stripe
.........................Actions
....................WePay
.........................Actions

**Comment by johannesschobel** [comment]
basically you just renamed `Sections` to `Containers`.. ^^

I know that this would be a handy feature, however, i believe that it results in rewriting huge parts of the framework..

**Comment by emanuellarini** [comment]
To follow 100% the Porto Pattern it MUST have a way to create Sections...

Imagine you have a multi tenant system, it's common to have 3 applications:
- Tenant member area
- Tenant admin area
- Multitenant master admin

How can this fit the currently apiato system?

**Comment by johannesschobel** [comment]
@emanuellarini : None of the discussed approaches are currently possible, because this would result in nearly rewriting apiato.. At the time of developing apiato, the `Section` was not introduced in `porto`... 

### Problem Statement
However, within my application I ran into the "same" (nearly) problem..
Consider my following (simplified) example:
* You have a Web-Shop that offers products.
* A `Customer` can browse available `Products` (i.e., he sees all "active" products)
* A `Manager` can manage products within a "backend" (i.e., management application). He, obviously, must see `all` (active & inactive) products in order to maintain and activate them

### Solution
What i did in my application. In order to illustrate this, i will just focus on the `Product` container, but it works the same for all other containers involved.. 
* I added a `CustomerController` (contains functions for the `Customer`) and a `ManagerController`, respectively.
* Further, i added a  `Customer` and `Manager` folder within the `UI/API/Routes` folder and categorized the existing routes accordingly. As the routes are just plain php files (without namespaces) this is easy (just move).
* Finally, you should change the function to be invoked from `Controller@yourCustomMethod` to `CustomerController@yourCustomMethod`
* I duplicated the required `Actions` for returning `GetAllProducts` and added customized Namespaces. For example, i added a `Customer` and `Manager` folder (and namespace) within the `Actions` folder!
* The `ManagerController` now only `Apiato::call()` `Actions` within the `Actions/Manager` namespace, the `CustomerController` only from the `Actions/Customer` namespace.

> HEADS UP!
> If you follow this approach, you **cannot** use the `Apiato::call(Controller@Class)` approach any more! You need to call it via `Apiato::call(FullNamespace\ActionOrTask::class)`!

That is the cleanest solution i found so far. This works (except the apiato-caller-style) out of the box and does not require any further adaptations! You may still use the existing `Generators` (however, you need to adapt the namespace of the generated classes!)

Finally, i found it to be "cleaner" to put everything into the container, instead of adding new "top level" applications on the same level as `Ship` or `Container`.
