### ISSUE TITLE
Auto-complate not working  in phpstorm

### ISSUE THREAD

**Issue by kvlknctk** [apiato/apiato#402]
## Expected Behavior
I want to use auto-complate with view(), route() methods. for this installed laravel plugin. normally working laravel >=5.

## Actual Behavior
it does not suggest completion to me.

## Steps to Reproduce the Problem

  1. re-install laravel plugin.
  2. generate ide helper code file with `php artisan ide-helper:meta`
  3. I watched the [laravel plugin](https://github.com/Haehnchen/idea-php-laravel-plugin) settings, 

  - Apiato Version: 7.2

## Additional Details
![screenshot_1](https://user-images.githubusercontent.com/10873815/38490817-cb8e3562-3bf2-11e8-8759-0e69bf2dcb37.png)

**Comment by johannesschobel** [comment]
Hey @kvlknctk ,

this is mainly because `ide-helper` is installed, but may not be correctly set up. You may check the `app/Ship/Configs/ide-helper.php` file for more configuration settings.

Problem is, that you need to "register" the Models.. As the models are scattered all over the application (in `App/Containers/*/Models`), this is quite complicated and not possible with `ide-helper` at the moment. So you may register the containers separately..

Hope this helps!?

**Comment by kvlknctk** [comment]
actually no, i want to auto complate only view and route method.

**Comment by johannesschobel** [comment]
yes, but this may be related to the fact, that apiato "scatters" its resources all over the entire application but not in one place / folder like a "normal" laravel application would do..

**Comment by bingalls** [comment]
@kvlknctk You can add class phpdoc @property comments, as appropriate, to each class, and make a pull request. This will help Phpstorm.
