### ISSUE TITLE
The question is where to do the transformation

### ISSUE THREAD

**Issue by yyyyeeeeesss** [apiato/apiato#410]
Hello! I have request API:

```
{
	"data":
	{
		"id": 232,
	       "lastName": "Sea",
	       "firstName" : "Nick",
	        "serving": "adults"
	}
}
```

Where is the best (Action, Request, Task) I can transform CamelCase name -> in shake_case name keys to write to the database?

**Comment by johannesschobel** [comment]
It is not clear to me, **what** you want to transform? The `keys` (e.g., `lastName`) or `values` (`Sea`) of the request data?!

Just my two cents on this:
I would NOT transform anywhere.. I would restrict the `Request` to send the data in a proper format. That means, the `client` should act the way the `api` is specified.. But that is just my opinion on this..

However, if you are not able to do this (e.g., because clients already exist and / or cannot be adapted properly) I would do it in the `Action` layer, in order to keep the `Task`s more reusable.. 
In this context, you may also provide a `GenericApplyShakeCaseTask`, that does something like this:

```php
/*
$data is an associative array that holds the data from your request - in your example like this:
[
   'id' => 232,
   'lastName' = 'Sea',
   'firstName' = 'nick',
   // more to go
]
*/
public function run(array $data) {
   // do some fancy transformation either with the KEYs or VALUES of the array, 
   // as i do not know, what you actually want to do!

   return $data;
}
```

and in your `Action` do it like this:
```php
public function run(Transporter $transporter) {
   // some stuff here

   $transformedData = Apiato::call(GenericApplyShakeCaseTask::class, [$requestData]);
   $result = Apiato::call(YourFancyTask::class, [$transformedData]);

   // more stuff to go
}

Hope this helps!?
Cheers
```

**Comment by yyyyeeeeesss** [comment]
Thanks! Yes, I need transform keys (e.g., lastName), because this style (CamelCase) is dictated by my employer in API. In the DB, I can not use the camelCase style in naming the columns of tables. Thank you. I will use Tasks.
