### ISSUE TITLE
Validate request failed, redirect to '/' ?

### ISSUE THREAD

**Issue by at-trungtran** [apiato/apiato#420]
Hey guys! 
I want to add a validate request on my form.And when it fail, i want to get a message response such as "name can not be empty", but i got a message 'Welcome to apiato'. I know where is that message , it's welcome message in '/', but i don't know why it appear.Why it redirect to '/' while validate request fail?
Please explain to me, thank !

**Comment by johannesschobel** [comment]
you are most likely not sending the `accept : application/json` header to the API.. This header is required in order to tell the API that you want to have a JSON document as response. If you do not properly use this header, the `web` routes will try to match - in your case this might fail and, therefore, you might get redirected to `/`.

**Comment by at-trungtran** [comment]
wow @johannesschobel , that's my problem.I  fixed it.Thank you very much !
