### ISSUE TITLE
OAuth returning Missing or invalid Access Token!

### ISSUE THREAD

**Issue by ErenPhayte** [apiato/apiato#421]
## Expected Behavior
Access token should be valid, as the token was just generated.

## Actual Behavior
Access token is being flagged as invalid.

## Steps to Reproduce the Problem

  1. Fresh install of APIATO as per instructions. 
  2. Used generated keys (apiato Personal Access Client) to get access token
  3. Access token is generated

## Specifications
NGINX, PHP 7.2 and MariaDB.

  - Apiato Version: latest

## Additional Details
After much debugging it turns out that when $token->getClaim('sub')  is called, the user_id is NULL.
I have tried to hardcode the user_id in the database too as i noticed in oauth_clients the user_id was NULL .. thinking this was causing the issue, but to no avail. Next step I guess is to check the token creation side of things, but wondered if there is something I am missing.

**Comment by johannesschobel** [comment]
Hey there..

I think, there might be some confusion with `Passport Client Secrets` and `OAuth Tokens`.. You need a valid `Passport Client Secret` in order to issue a proper `OAuth Token` with your current username/password combination.. 

Did you run:
```
php artisan migrate
php artisan db:seed
php artisan generate:key
php artisan passport:install
```

the last command (`passport:install`) will create some client keys to be sent via the `login` route in order to correctly authenticate..

Both, the `client_id` and `client_secret` must be passed to the `login` route.. Check out this doc page in particular: http://docs.apiato.io/features/authentication/#how-to-get-access-token-using-oauth-20

Hope this helps!?

**Comment by ErenPhayte** [comment]
thanks for the quick response! I did run all those commands. What I am after is setting up Client Credentials (For third-party clients  - server to server comms), that just require the keys. I will see if the login route will work.

**Comment by ErenPhayte** [comment]
I will try a different version of the platform as I also just noticed trying to login to dashboard throws a Class 'App\Containers\Authentication\Actions\Apiato' not found

**Comment by johannesschobel** [comment]
You may need to include the apiato facade

**Comment by ErenPhayte** [comment]
I installed LTS version - worked out the box, although the dashboard is
empty - will investigate later why that is.
However I managed to solve the client credentials issue. I registered
CheckClientCredentials in $routeMiddleware  and then attached that
middleware to instead of auth:api like this:

'middleware' => [
   'client',
],


Works now!

**Comment by johannesschobel** [comment]
The dashboard is empty.. no content there.. you need to fill it with your application content ;)

Glad you managed to solve the issue :)
