### ISSUE TITLE
Performance boost with swoole

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#422]
Since apiato is a heavy framework meant for api's we should look into optimizing it for speed. I've looked into PHP-PM (https://github.com/php-pm/php-pm) & Swoole (https://github.com/swooletw/laravel-swoole).

Swoole is getting a lot of attention lately (https://laravel-news.com/laravel-swoole) so we might want to start integrating apiato with it?

Tests on a macbook increased the requests/second from 80 to 8700. Needless to say it's worth looking into ;)

**Comment by johannesschobel** [comment]
Hey @deviouspk , wow, that really looks impressive! 

Does this require a "new" server or the additional installation of packages within the server itself? From your initial post i assume you already got it to work? What changes are required for apiato itself? Can we "simply" provide a detailled "how to install" in the docs or are code-changes required?
How can we implement these changes in order to **not break** existing applications and **not** make `swoole` a new dependency for apiato?

Can you provide me with more details on this? Cool stuff!

Thank you very much and cheers!

**Comment by deviouspk** [comment]
Hey johannes!
I havn't tried it on apiato yet only on laravel :( but swoole is a pecl extension and it kinda works like a dedicated http server. It basically boots one instance of your application once so it doesn't need to be reloaded every time. Would be really cool if we got it to work with apiato. I'll test it :)

**Comment by johannesschobel** [comment]
Hey there.. first of all, it is awesome that you managed to (nearly) get it to work.. 
I have read a few articles regarding `Swoole` - that is really impressive..

However, i have some major concerns with it:
1) It is linux / osx exclusive.. There is currently no windows build
2) It does not work "out of the box" (e.g., you need to install software "on your server" - not in your project!). Not mentioning the configuration effort
3) It requires another "programming paradigm" (e.g., you may need to "clean up" your application / variables yourself, because everything is cached)..

Especially, 2 is critical, i think.. Because this would not allow for installing an apiato application on nearly any webhoster out there, because you would require you to have a `Swoole` server.. As far as I have understood, `Swoole` is a dedicated http server that runs **not** within `Apache` or `NginX`, but is a standalone software?!

So i would make this completely optional.. If you manage to get it to run smoothly, we could add a `how-to` article to the docs in order to show people how to use `swoole` and so on. Maybe this page here would be a good starting-point? http://docs.apiato.io/getting-started/installation/#Development-Environment

Kind Regards

**Comment by heikezy** [comment]
it should be optional.

Swoole works under CLI mode, which means it won’t have anything to do with PHP-fpm. What it does is just as simple as what NodeJs can do in some sort of ways, providing an asynchronous non-eventblocking server or client. It’s like a socket library that comes with a whole package, including http server, websocket server, and many cool features that php has never been able to do.

But, it indeed takes extra effort to install it, since it’s a php extension. And you won’t be able to use it unless you’ve got the full access of your linux server other than just some php hosting. And since swoole is included in the pecl pack, so once you know how to do linux stuffs right, installing it should be quite simple.

Aside from environmental requirements, a bigger issue is the changes of ways of PHP programming. Coding with swoole is nothing like normal FPM mode, because: First, it’s in CLI mode. So once codes are loaded, normally they would just stay in memory. Before, we would like to change the codes and expect to see changes of the result immediately. But for CLI, you have to reload the new codes since old ones could still be there. And also, memory leaking problem could be more serious. Why is that? Because for PHP coder, that wasn’t an issue before, once php script is done being interpreted, the php process is killed, memory is realeased. Even if there is a memory leaking problem, it is solved after a very short request time. But for CLI mode, any small amount of memory leaking could add up to a very considerable amount. But don’t worry we have methods to solve the two issues above, swoole has been very considerate.
The problem that we can’t avoid is about multiprocess. Yes, one of the reasons that swoole is working so effectively is that it supports multiprocessing. But it also means Singleton may not be Singleton anymore, there could be one Singleton for each process. The change in one of them may not affect any other ones. Mulprocess may need to communicate with each other. Luckily, swoole provides tools for that.
So, what I’m saying is that apiato definitely need to change some of its code to be able to run on swoole. And unpredictable exceptions may occur. And there could be compatibility issues for packages from composer which are not designed for swoole.

I personally think speeding up apiato with swoole is a good idea. And it should be an option for most users. But it may take time to make this solution stable.

**Comment by heikezy** [comment]
And also check this project out, https://github.com/hhxsv5/laravel-s
It is also a project that tries to speed up laravel/lumen by swoole but with more cool features coming from swoole, like multiprocessing asynchronous task workers, websocket server, tcp/udp scalable and timer.

Hope these information helps.

**Comment by wangdeer** [comment]
> And also check this project out, https://github.com/hhxsv5/laravel-s
> It is also a project that tries to speed up laravel/lumen by swoole but with more cool features coming from swoole, like multiprocessing asynchronous task workers, websocket server, tcp/udp scalable and timer.
> 
> Hope these information helps.

So, now can we using laravel-s with apiato ?
