### ISSUE TITLE
The difference between Transporter and Transformer

### ISSUE THREAD

**Issue by Osub** [apiato/apiato#425]
The difference between Transporter and Transformer ？

**Comment by johannesschobel** [comment]
Hey,

this is pretty well covered in the docs:
- [Transformers](http://docs.apiato.io/components/transformers/)
- [Transporters](http://docs.apiato.io/components/transporters/)

In short: 
- `Transporters` are some kind of `DTO` (Data Transfer Object) that can be used in order to pass it between the different "layers" (`Controller > Action > Task`) within apiato. E.g., it is "bad" to pass the `Request` from the `Controller` to the `Action`, because this would result in issues when testing the `Action` (because you would need to create a `Request` just to test the `Action`!)
- `Transformers`, on the other, are used to "transform" your internal `Model` to a respective output representation (e.g., to a `DataArray`) using a defined `Serializer`
