### ISSUE TITLE
Question: Nested Set Model With Apiato

### ISSUE THREAD

**Issue by dineshbabu179** [apiato/apiato#426]
I planing to start new project and most likely to use apiato. I am not Laravel Expert, but as an architect of the project, evaluating how this framework will adopt certain data model like Nested Set. As a Proof of concept, we are planing to build organization Hierarchy Application. 

    root
      |_ Child 1
        |_ Child 1.1
        |_ Child 1.2
              |_ Child 1.2.1
              |_ Child 1.2.2
      |_ Child 2
        |_ Child 2.1
        |_ Child 2.2

As a framework apiato has been inherited from Laravel.  After some research we found suitable package [laravel nestedset](https://github.com/lazychaser/laravel-nestedset). At this point, we really don't know how complex the implementation, but worth trying out, rather than simple traditional approach of referring child with parent_id.

Do you thing apiato will adopt Nested Set Model? Any other alternative recommendation of implementing this model set.

**Comment by johannesschobel** [comment]
Hey there.. In my application (that uses apiato as foundation), i have built a `Category` container that uses a `NestedSet` implementation. I think, i used the same one as you mentioned - but not sure..

Apiato does (and will) NOT support `NestedSet` out of the box, but you can easily add it on your own. Create a container, add your own functionality and you are ready to go..

You may need to apply some of the `Model Traits` from `apiato` to your custom `NestedSetModel` in order to make it work.. However, this is quite easy.. 

Good luck and have fun!
