### ISSUE TITLE
installation in different directory

### ISSUE THREAD

**Issue by mendizalea** [apiato/apiato#430]
## Expected Behavior
I have installed in a shared hosting. The structure of the folders would be:
/Apps/apiato/[apiato install dir]
/www/api/[these is the public folder]

I modified the index.php

require __DIR__.'/../../Apps/apiato/vendor/autoload.php';
$app = require_once __DIR__.'/../../Apps/apiato/bootstrap/app.php';

## Actual Behavior
When I go into admin.myweb.com/api and login, redirect me to admin.myweb.com/login and no to admin.myweb.com/api/login

## Specifications
  - Apiato Version: 7.4.7

Thanks

**Comment by mendizalea** [comment]
I'm not calling any api. I am accessing the web environment, which according to installation is http://admin.apiato.dev, but mine is https://admin.miweb.com/api, but once the login is introduced it redirects me to https: // admin .miweb.com / login and not to https://admin.miweb.com/api/login

Thanks you

**Comment by johannesschobel** [comment]
aaaaaaaaaaaaah.. i think, i once read an issue that is closely realted, however, i dont find it at the moment..

However, the problem was as follows: After a (successfully) login, passport automatically redirects to `/login`. This behaviour was customizable in a previous version of passport (or is related to laravel? Not sure!), but it got changed to a hardcoded URL - so noone can change this URL! That is so typical for laravel ;)

A PR that addresses this issue (i.e., it would make the URL customizable) got closed within hours from taylor.. i remember this, because it was so f*cking hillarious..
