### ISSUE TITLE
Subaction generate in action namespace

### ISSUE THREAD

**Issue by aqualaguna** [apiato/apiato#436]
## Expected Behavior
Subaction class generate in subaction folder

## Actual Behavior
subaction class created in action folder

## Steps to Reproduce the Problem

  1. php artisan apiato:generate:subaction --container=Journal

## Specifications

  - Apiato Version: 7.2

## Additional Details
after i call subaction from apiato::call() it said subaction should be in subaction folder (namespace) is this new feature?

**Comment by johannesschobel** [comment]
That is due to some "black magic" within `apiato/core` and the `apiato-caller-style` (i.e., `Apiato::call('Container@ActionOrTask')`)..

Basically, what it does, is the following thing:
It extracts the Container (i.g., `Container') and Class to be called (`ActionOrTask` from the above example). Next, it takes the **last** part of the Class that is written in capitals (i.e., `Task`) and builds a fully qualified classname from all respective parts. The FQCN, in the above mentioned example would be:
```php
App\Containers\{{container-name}}\{{class-type}}s\{{class-name}}
```
with
```
container-name = Container
class-type = Task
class-name = ActionOrTask
```

You are most likely have named your Class something like this: `MyFancySubaction` - which results in the fact, that it tries to search in the `Subactions` namespace - which is not present!

There are 2 easy fixes:
1) Just write it as `MyFancySubAction`: This will tell the function to search within the `Actions` folder, where this class is located
2) Don't use the `apiato-caller-style` method and call it like this: `Apiato::call(MyFancySubaction::class)`

Cheers
