### ISSUE TITLE
Revisit Auto-Discovery and Config loading

### ISSUE THREAD

**Issue by sudiptochoudhury** [apiato/apiato#443]
I am using Laravel 5.6 .25 and have removed “*” from the `dont-discover`. 

I checked using tinker that the configs defined in Containers and Ship directories are accessible - hence are loading.

Can this be rechecked and confirmed so that I can keep using Auto-Discovery?

Info: I had checked out `apiato/apiato` a few days back and moved the `Core` from `vendor` to `app` directory - if that information is of any requirement.

**Comment by johannesschobel** [comment]
I just tested in my "production" application to remove the `dont-discover => '*'` attribute from the `composer.json` file. This resulted in loading the `config` files in a wrong order.

For example, the `hash-id` length is set to 2, instead of 20 (as in my own `hashid` config file. Further, all config values are set to "default"..

Maybe this works for you, because you copied the `vendor/apiato` folder to your `app` folder.. don't know..

Can you try with a completely fresh / clean apiato installation and remove the `dont-discover` property, to see the behaviour..
