### ISSUE TITLE
Bug in Testing with DB connection testing_sqlite_in_memory 

### ISSUE THREAD

**Issue by deviouspk** [apiato/apiato#462]
## Expected Behavior
When running tests the database should only be seeded once.

## Actual Behavior
I didn't notice it until i had some very big seeders running on my tests. If you specify the DB_CONNECTION env variable to "testing_sqlite_in_memory" it will reseed the database for every test.

## Steps to Reproduce the Problem
When you run tests with phpunit and specify the DB_CONNECTION env variable to "testing_sqlite_in_memory"

## Specifications
Latest version of apiato + laradock (nginx, redis, mariadb, mongo) to run everything

**Comment by johannesschobel** [comment]
I wouldn't consider this as a bug, but i can confirm this. 
In my opinion, this is a proper behaviour, as you do not want to have "side-effects" in the data stored in your database.

Consider the following example:
You have a seeder that creates 4 `Posts` in the database. Then you have a test, that checks, if all 4 Posts are stored within the database. However, later, you add a test to "create a new post" manually via your `Action`. Suddenly, your "check if 4 posts are in the database" may fail, because the tests now **highly depend on the order of their execution**.

I "worked around" this, by only seeding the data i need for this specific test..

**Comment by deviouspk** [comment]
Hmm it was kinda confusing because this is not default laravel behavior. We should atleast have an option to disable this no? maybe by specifying another db_connection? for example: testing_sqlite_in_memory_seed_once ?

**Comment by Mahmoudz** [comment]
`testing_sqlite_in_memory` was removed in Apiato 8.0. Check the new setup even if you don't want to upgrade and should work.
