### ISSUE TITLE
API Auth not working

### ISSUE THREAD

**Issue by oriske** [apiato/apiato#530]
After Vanilla install and Using Postman collection i am able to Login to Dashboard and to Login via Postman
Token is returned.
All subsequent Get requests end with error:

 "message": "An Exception occurred when trying to authenticate the User.",
    "errors": "Missing or invalid Access Token!",
    "status_code": 401,
    "exception": "App\\Containers\\Authentication\\Exceptions\\AuthenticationException",
    "file": "/home/www-data/hosts/apiato/app/Ship/Middlewares/Http/Authenticate.php",
    "line": 22,

Post Request to register new user is possible.
What is wrong here?

**Comment by yalsicor** [comment]
Did you send the token you got as Authorization header in subsequent requests?

[Postman Bearer token](https://learning.getpostman.com/docs/postman/sending-api-requests/authorization/#bearer-token)

**Comment by hermesfelipe** [comment]
hello,
I am getting the same error.
After loging in the token is saved in the session, but the "user" method of class "SessionGuard" (/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php) is not able to retrieve the user from the saved session.

The problem seems to be in line 135 of this file:

`$id = $this->session->get($this->getName());` 

After this call, $id is null. 

`$this->getName()` returns the name of the session, which is stored in the session file under /storage/framework/sessions.

the `$this->session->get()` method being called is implemented in class Store (/vendor/laravel/src/Illuminate/Session/Store.php) which calls "Arr::get($this->attributes, $key, $default)". 

When `$this->session->get()` runs in class Store, it looks for the sassion name (a string like "login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d") in the array "$this->attributes" but the key does not exist.

This is as far as I was able to go into this - I'm a newbie to laravel and newbi_er_ to apiato...

**Comment by hermesfelipe** [comment]
by the way, I'm trying to login with the login form from the admin dashboard, untouched. Admin user has been granted the access-dashboard role (through `php artisan apiato:permissions:toRole admin`).

**Comment by hermesfelipe** [comment]
After many hours of debugging, a lot of swearing and after almost giving up on using apiato for this project, I found the problem.

In file app/config/auth.php, change the driver of the api guard to 'passport'.

`    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',   // <== change here
            'provider' => 'users',
            'hash' => false,
        ],
    ],`

and voilá! Authentication is working now :)

Not sure apiato is supposed to use the 'token' driver, I just know it started work with the 'passport' driver.

**Comment by Te7a-Houdini** [comment]
@hermesfelipe  thanks alot for your answer . and the default driver should be passport . as this issue happened before [here](https://github.com/apiato/apiato/issues/527)

**Comment by hermesfelipe** [comment]
thank you @Te7a-Houdini , I have submitted a PR (Fix auth. issue - change token driver to passport #532) to fix this issue. Hopefully I did it right.

@yalsicor , pls let me know if the PR needs any fixing. #532

**Comment by kira0012** [comment]
{"status":"error","code":0,"message":"An Exception occurred when trying to authenticate the User.","errors":"Missing or invalid Access Token!","status_code":401} 

can't retrieve data
![Screenshot from 2020-04-21 15-34-50](https://user-images.githubusercontent.com/45187580/79838476-a78ce680-83e5-11ea-8a9b-f7ad8c19821e.png)

**Comment by yalsicor** [comment]
Please open a new Issue and provide more information. What version, how did you install, what is the request? What did you try so far to solve the issue?
