### ISSUE TITLE
Apidoc Config is not read by Apidocjs

### ISSUE THREAD

**Issue by Elshaden** [apiato/apiato#572]
### Description:
With New Apitao Version, Apidocs does not read the configuration file

### Expected Behavior:
render the Header and footer
### Additional Context:
When running the apiato:apidoc it only renders the routes, not the header and footer from the preset in apidoc.json file in the Documentation container.
warning  
``` 

[private] apidoc -c app/Containers/Documentation/ApiDocJs/private -f private.php -f public.php  -i app -o public/xxx-xxx/private/documentation
Output: {"message":"Please create an apidoc.json configuration file.","level":"warn"}

```
even though the json file is there
when I run the apidoc generate command, it  gives error 
```
 message":"parser plugin 'return' not found in block: XX in file
```
I think that the config (documentation-container.php) file is not read by the Apidoc js .

### Versions:
- Apiato Version: 9
- PHP Version: 7..2

**Comment by zmaren** [comment]
Hi @Elshaden, I tried to debug this and I found the issue in **package_info.json** of the apidoc library in node_modules.

@Mahmoudz, I tried to compare two files form the installed version in Apiato and from the current version on github. There is a difference.

Line 69: https://github.com/apidoc/apidoc/blob/master/lib/package_info.js
Line 61: https://i.imgur.com/fhnjfnL.png - apidoc in the current version of Apiato

The fix for Apiato version is this: https://i.imgur.com/4G3hVtr.png

Bug: https://i.imgur.com/WsFT1Dd.png

Console log of the `app.options.config` in the old vs the new version of Apiato:

Old: https://i.imgur.com/z5vsTTr.png
New: https://i.imgur.com/hLoi7eM.png

Old version is 8.0

**Comment by yalsicor** [comment]
Thanks @Elshaden for your efforts. I do not know, if I do fully understand your contribution.

The change you are proposing is in the apidoc package? Is there a possible fix for apiato that does not involve changing a dependency package?

Changing the apidoc version to a newer one does not seem to fix the problem.

I do not fully understand waht the process behind this is and at what part it breaks. Can you elaborate more on that?

**Comment by Elshaden** [comment]
Hi @yalsicor 
Current Version of Apiato has a Bug in Apidoc. Documentation
![image](https://user-images.githubusercontent.com/33955172/88243396-937cad80-cc90-11ea-9a57-e397c2d103c9.png)

@zmaren  thankfully found what the bug was, being a difference in the Apidocs version.

**Comment by zmaren** [comment]
Not even that. With this bug you cannot specify either private or public endpoints, or even any custom endpoint like shared etc.

**Comment by Mohammad-Alavi** [comment]
@egbertmza [found and fixed](https://github.com/apiato/apiato/issues/565#issuecomment-646523122) this issue but i prefer to wait and see what @Mahmoudz thoughts are on this.

**Comment by Mahmoudz** [comment]
@Mohammad-Alavi I've approved your PR. I would say if you have a solution to any issue, please submit a PR and get it merged. Don't wait for me to review it, as I'm not always available anymore. Thanks.

**Comment by Mohammad-Alavi** [comment]
#577 Should fix this issue.
