### ISSUE TITLE
Integrate https://sentry.io/

### ISSUE THREAD

**Issue by rasyid46** [apiato/apiato#683]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi can you explain integrate [sentry](https://sentry.io/) for logger error
**Describe alternatives you've considered**

**Additional context**

**Comment by Mohammad-Alavi** [comment]
Hey! Just follow the sentry docs. It is exactly the same as Laravel. The only difference is the location of the exception handler file which in Apiato is located [here](https://github.com/apiato/apiato/blob/11.x/app/Ship/Exceptions/Handlers/ExceptionsHandler.php).

**Comment by rasyid46** [comment]
thank for advice 
definitely i use apiato v 9.0.0

https://github.com/apiato/apiato/blob/9.0/app/Ship/Exceptions/Handlers/ExceptionsHandler.php

i try add   repot function  like this (https://gist.github.com/rasyid46/6389e6fbed6ce4115ed0873bd9f65a8c)

after that my scren blank

**Comment by Mohammad-Alavi** [comment]
Oh man. I cant remember anything about v9. The exception handling is refactored/fixed and changed a lot since then and it is almost completely something else in v11 which i tried to make it as close as I could to Laravel.

I am using Sentery on another project with Laravel 7 and I think Apiato 6. This is a piece of my code in the exception handers implementing Sentery. It might help.

```
  public function report(Throwable $exception)
  {
    if ($this->shouldReport($exception) && app()->bound('sentry')) {
      app('sentry')->captureException($exception);
    }

    parent::report($exception);
  }
  ```
