### ISSUE TITLE
microservice projects

### ISSUE THREAD

**Issue by Aliakbari1994** [apiato/apiato#702]
I want to code as a microservice. Therefore, I need each section to have its own database. How can I solve this problem in the local environment where all the services are in the same project?

**Comment by mderis** [comment]
Hello @Aliakbari1994 
Having multi databases, each for a section is not supported in apiato so far.

**Comment by Mohammad-Alavi** [comment]
@Aliakbari1994 
One of the easiest ways to start this process with is to use a multi schema capable DB and only have one DB with multiple schema for each section instead of having a DB per section.

When you are ready to move to microservices then you can extract each schema to its own DB.

This approach will free you from the pain of having multiple DB from the beginning. 

Please note that sections should never directly contact each other and should be totally decoupled. One solution for this is to use events for the interaction between sections.
